import type { Metadata } from 'next';
import Link from 'next/link';
import './styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="menu">
          <Link href="/">Home</Link>
          <Link href="/books">List of books</Link>
          <Link href="/admin/books/new">Create a new book</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
